global:
  scrape_interval: 60s
  scrape_timeout: 10s

scrape_configs:
  - job_name: ktb-backend
    sample_limit: 5000
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 127.0.0.1:5001
        labels:
          application: ktb-chat-backend
          host: __HOSTNAME__